package com.wondersgroup.framework.cxf.materialservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-04-15T15:33:45.451+08:00
 * Generated source version: 3.3.1
 *
 */
@WebService(targetNamespace = "http://www.inte.material.hcfa.com", name = "MaterialService")
@XmlSeeAlso({ObjectFactory.class})
public interface MaterialService {

    @WebMethod
    @RequestWrapper(localName = "getWLInfo", targetNamespace = "http://www.inte.material.hcfa.com", className = "com.wondersgroup.framework.cxf.materialservice.GetWLInfo")
    @ResponseWrapper(localName = "getWLInfoResponse", targetNamespace = "http://www.inte.material.hcfa.com", className = "com.wondersgroup.framework.cxf.materialservice.GetWLInfoResponse")
    @WebResult(name = "String", targetNamespace = "")
    public java.lang.String getWLInfo(
        @WebParam(name = "para1", targetNamespace = "")
        java.lang.String para1
    );

    @WebMethod
    @RequestWrapper(localName = "getDWInfo", targetNamespace = "http://www.inte.material.hcfa.com", className = "com.wondersgroup.framework.cxf.materialservice.GetDWInfo")
    @ResponseWrapper(localName = "getDWInfoResponse", targetNamespace = "http://www.inte.material.hcfa.com", className = "com.wondersgroup.framework.cxf.materialservice.GetDWInfoResponse")
    @WebResult(name = "String", targetNamespace = "")
    public java.lang.String getDWInfo(
        @WebParam(name = "para2", targetNamespace = "")
        java.lang.String para2
    );
}
