package com.wondersgroup.framework.cxf.centerservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-06-13T16:24:34.794+08:00
 * Generated source version: 3.3.1
 *
 */
@WebService(targetNamespace = "http://www.WebService.demo.example.com", name = "CommonService")
@XmlSeeAlso({ObjectFactory.class})
public interface CommonService {

    @WebMethod
    @RequestWrapper(localName = "getBigClasss", targetNamespace = "http://www.WebService.demo.example.com", className = "com.wondersgroup.framework.cxf.centerservice.GetBigClasss")
    @ResponseWrapper(localName = "getBigClasssResponse", targetNamespace = "http://www.WebService.demo.example.com", className = "com.wondersgroup.framework.cxf.centerservice.GetBigClasssResponse")
    @WebResult(name = "String", targetNamespace = "")
    public java.lang.String getBigClasss(
        @WebParam(name = "QueryName2", targetNamespace = "")
        java.lang.String queryName2
    );

    @WebMethod
    @RequestWrapper(localName = "getSupplier", targetNamespace = "http://www.WebService.demo.example.com", className = "com.wondersgroup.framework.cxf.centerservice.GetSupplier")
    @ResponseWrapper(localName = "getSupplierResponse", targetNamespace = "http://www.WebService.demo.example.com", className = "com.wondersgroup.framework.cxf.centerservice.GetSupplierResponse")
    @WebResult(name = "String", targetNamespace = "")
    public java.lang.String getSupplier(
        @WebParam(name = "QueryName6", targetNamespace = "")
        java.lang.String queryName6
    );

    @WebMethod
    @RequestWrapper(localName = "getSmallClasss", targetNamespace = "http://www.WebService.demo.example.com", className = "com.wondersgroup.framework.cxf.centerservice.GetSmallClasss")
    @ResponseWrapper(localName = "getSmallClasssResponse", targetNamespace = "http://www.WebService.demo.example.com", className = "com.wondersgroup.framework.cxf.centerservice.GetSmallClasssResponse")
    @WebResult(name = "String", targetNamespace = "")
    public java.lang.String getSmallClasss(
        @WebParam(name = "QueryName4", targetNamespace = "")
        java.lang.String queryName4
    );

    @WebMethod
    @RequestWrapper(localName = "insertMaterielInfo", targetNamespace = "http://www.WebService.demo.example.com", className = "com.wondersgroup.framework.cxf.centerservice.InsertMaterielInfo")
    @ResponseWrapper(localName = "insertMaterielInfoResponse", targetNamespace = "http://www.WebService.demo.example.com", className = "com.wondersgroup.framework.cxf.centerservice.InsertMaterielInfoResponse")
    @WebResult(name = "String", targetNamespace = "")
    public java.lang.String insertMaterielInfo(
        @WebParam(name = "QueryName1", targetNamespace = "")
        java.lang.String queryName1
    );

    @WebMethod
    @RequestWrapper(localName = "getMaterielInfo", targetNamespace = "http://www.WebService.demo.example.com", className = "com.wondersgroup.framework.cxf.centerservice.GetMaterielInfo")
    @ResponseWrapper(localName = "getMaterielInfoResponse", targetNamespace = "http://www.WebService.demo.example.com", className = "com.wondersgroup.framework.cxf.centerservice.GetMaterielInfoResponse")
    @WebResult(name = "String", targetNamespace = "")
    public java.lang.String getMaterielInfo(
        @WebParam(name = "QueryName", targetNamespace = "")
        java.lang.String queryName
    );

    @WebMethod
    @RequestWrapper(localName = "insertBigClasss", targetNamespace = "http://www.WebService.demo.example.com", className = "com.wondersgroup.framework.cxf.centerservice.InsertBigClasss")
    @ResponseWrapper(localName = "insertBigClasssResponse", targetNamespace = "http://www.WebService.demo.example.com", className = "com.wondersgroup.framework.cxf.centerservice.InsertBigClasssResponse")
    @WebResult(name = "String", targetNamespace = "")
    public java.lang.String insertBigClasss(
        @WebParam(name = "QueryName3", targetNamespace = "")
        java.lang.String queryName3
    );

    @WebMethod
    @RequestWrapper(localName = "insertSupplier", targetNamespace = "http://www.WebService.demo.example.com", className = "com.wondersgroup.framework.cxf.centerservice.InsertSupplier")
    @ResponseWrapper(localName = "insertSupplierResponse", targetNamespace = "http://www.WebService.demo.example.com", className = "com.wondersgroup.framework.cxf.centerservice.InsertSupplierResponse")
    @WebResult(name = "String", targetNamespace = "")
    public java.lang.String insertSupplier(
        @WebParam(name = "QueryName7", targetNamespace = "")
        java.lang.String queryName7
    );

    @WebMethod
    @RequestWrapper(localName = "insertSmallClasss", targetNamespace = "http://www.WebService.demo.example.com", className = "com.wondersgroup.framework.cxf.centerservice.InsertSmallClasss")
    @ResponseWrapper(localName = "insertSmallClasssResponse", targetNamespace = "http://www.WebService.demo.example.com", className = "com.wondersgroup.framework.cxf.centerservice.InsertSmallClasssResponse")
    @WebResult(name = "String", targetNamespace = "")
    public java.lang.String insertSmallClasss(
        @WebParam(name = "QueryName5", targetNamespace = "")
        java.lang.String queryName5
    );
}
